Layoutを出し分け
Qin-Eva/pj_engivia pull request #62
Opened 2021-11-15 14:59 UTC by yugo-ibuki

レイアウト出し分けしましたァー！

broadcastに関しては今PR出てるので、コンフリクト起こりそうだったので触ってないです！！！

2021-11-15 21:48 UTC, kijikunnn commented
確認します！！

2021-11-15 22:04 UTC, kijikunnn requested changes

2021-11-15 22:04 UTC, kijikunnn commented on src/pages/admin/broadcasts/create.tsx
> +  return <Layout> {page}</Layout>
"{"の前にスペースがあるので削除おねがいします！

2021-11-16 11:38 UTC, yugo-ibuki commented on src/pages/admin/broadcasts/create.tsx
> +  return <Layout> {page}</Layout>
直しました！

2021-11-16 12:23 UTC, kijikunnn approved these changes
LGTM!

2021-11-16 12:23 UTC, merged