Issue/94
Qin-Eva/pj_engivia pull request #98
Opened 2021-12-05 06:30 UTC by choist5

## やったこと
* 投稿詳細ページの実装
* 投稿編集ページの実装

## 仕様とか備考
* http://localhost:3000/broadcasts
から順番に遷移すれば見れると思います。
* 放送一覧からどれかをクリックすれば投稿詳細画面に遷移しますが、ログインユーザの選択した放送の投稿（post）がなければ作成画面に遷移するようにしています。
　※この仕様も投稿詳細画面でするのではなく放送一覧で選択した時に遷移先を決めたほうがいいと思いますが。。
* 自分の投稿があれば詳細画面が見れます。
* データの持ち方は放送一覧の「第20回エンジビアの泉」の関連データ（stream、posts、users）を見てもらえれば。

## 全体
* 詳細画面の「削除後」、編集画面の「保存後」、「キャンセル後」の遷移先はこれでいいのか、をご確認ください。
* lib内も触ってますが、詳細、編集画面で使うためのソースになってますのでリファクタリングが必要かもです。
* 今回もfirebase、typescriptを掴めず、エラーを消すためのソースになっている可能性もありますのですみません。

## issue
close #94

2021-12-11 12:39 UTC, kijikunnn requested changes
確認が遅くなり申し訳ございません🙇‍♂️

あと，コンフリクトが出ているので，こちらの修正もお願い致します

2021-12-11 12:39 UTC, kijikunnn commented on src/pages/posts/detail/[id].tsx
> +import router, { useRouter } from 'next/router'
routerとuseRouterはどちらも同じように使える気がするので，
```js
const router = useRouter
```
で，このrouterでもquery.idを取得できた気がするので，routerかuseRouterのどちらかに修正お願いします🙇‍♂️

2021-12-11 13:25 UTC, choist5 commented on src/pages/posts/detail/[id].tsx
> +import router, { useRouter } from 'next/router'
レビューありがとうございます。
コンフリクトとrouterを修正しました。
ご確認お願いします。

2021-12-11 14:05 UTC, kijikunnn approved these changes
LGTM👍

2021-12-11 14:06 UTC, kijikunnn commented
src/pages/posts/detail/[id].tsx
src/pages/posts/edit/[id].tsx
の2つでまだコンフリクトが残っていそうですね💦
こちらのファイルの確認もよろしくお願いします🙇‍♂️

2021-12-11 14:30 UTC, choist5 commented
ごめんなさい🙇ちょっとコンフリクトの解消の仕方が分かりませぬ。。
「This branch has conflicts that must be resolved」の右にある「Resolve conflicts」ボタンを押すとコンフリクトしている箇所が表示されるんですかね？
ここは先ほどコミットした箇所なんですが、、他のところですかね？

2021-12-11 14:36 UTC, choist5 commented
もしかしたらこれで、いけたのかもしれない。。
よろしくお願いします🙇

2021-12-12 02:12 UTC, kijikunnn commented
@choist5 
返信遅くなり申し訳ございません🙇‍♂️
コンフリクトも解消できたみたいなのでマージさせていただきます！

2021-12-12 02:12 UTC, merged